
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Workbyclocklib.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BookingPayment
{

    public int BookingPaymentId { get; set; }

    public int BookingId { get; set; }

    public int PaymentTypeId { get; set; }

    public decimal PaymentAmount { get; set; }

    public System.DateTime PaymentDate { get; set; }

    public string PaymentAcceptedBy { get; set; }



    public virtual PaymentType PaymentType { get; set; }

    public virtual RoomBooking RoomBooking { get; set; }

}

}
