
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Workbyclocklib.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {

        this.EmployeeLocations = new HashSet<EmployeeLocation>();

        this.EmployeeTimeCards = new HashSet<EmployeeTimeCard>();

    }


    public int EmployeeId { get; set; }

    public int EmployeePin { get; set; }

    public string EmployeeName { get; set; }

    public string EmployeeEmail { get; set; }

    public string EmployeePhone { get; set; }

    public Nullable<int> EmployeeLastFour { get; set; }

    public Nullable<int> EmployeeEmploymentTypeId { get; set; }

    public Nullable<bool> EmployeeIsHourly { get; set; }

    public Nullable<float> EmployeeRate { get; set; }

    public Nullable<System.DateTime> EmployeeBirthDate { get; set; }

    public Nullable<System.DateTime> EmployeeHireDate { get; set; }

    public Nullable<System.DateTime> EmployeeLeftDate { get; set; }

    public string EmployeeAddress1 { get; set; }

    public string EmployeeAddress2 { get; set; }

    public string EmployeeCity { get; set; }

    public string EmployeeState { get; set; }

    public string EmployeeZip { get; set; }

    public string EmployeeCountry { get; set; }

    public System.DateTime CreateDate { get; set; }

    public bool Active { get; set; }



    public virtual EmploymentType EmploymentType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeLocation> EmployeeLocations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeTimeCard> EmployeeTimeCards { get; set; }

}

}
