
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Workbyclocklib.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeTimeCardHistory
{

    public int EmployeeTimeCardHistoryId { get; set; }

    public int EmployeeTimeCardId { get; set; }

    public int EmployeeId { get; set; }

    public int LocationId { get; set; }

    public string LocationIp { get; set; }

    public Nullable<System.DateTime> TimeIn { get; set; }

    public Nullable<System.DateTime> TimeOut { get; set; }

    public System.DateTime TimeCardCreateDate { get; set; }

    public System.DateTime CreateDate { get; set; }

    public string DeviceCode { get; set; }

    public Nullable<System.DateTime> TimeInUtc { get; set; }

    public Nullable<System.DateTime> TimeOutUtc { get; set; }

    public string DeviceCodeOut { get; set; }

    public string Reason { get; set; }

    public string UpdateUser { get; set; }

    public string Action { get; set; }

}

}
