
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Workbyclocklib.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Guest
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Guest()
    {

        this.RoomBookings = new HashSet<RoomBooking>();

    }


    public int GuestId { get; set; }

    public string GuestFullName { get; set; }

    public string GuestPhone { get; set; }

    public string GuestEmail { get; set; }

    public bool IsDNR { get; set; }

    public string GuestAddress { get; set; }

    public string GuestDriverLicenseId { get; set; }

    public Nullable<int> CompanyId { get; set; }



    public virtual Company Company { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RoomBooking> RoomBookings { get; set; }

}

}
