
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Workbyclocklib.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Location
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Location()
    {

        this.CompanyLocations = new HashSet<CompanyLocation>();

        this.EmployeeLocations = new HashSet<EmployeeLocation>();

        this.EmployeeTimeCards = new HashSet<EmployeeTimeCard>();

        this.Devices = new HashSet<Device>();

        this.BookingTypes = new HashSet<BookingType>();

        this.RoomBookings = new HashSet<RoomBooking>();

        this.Rooms = new HashSet<Room>();

        this.TaxInfoes = new HashSet<TaxInfo>();

    }


    public int LocationId { get; set; }

    public string LocationName { get; set; }

    public string LocationDescription { get; set; }

    public string LocationPhone { get; set; }

    public string LocationEmail { get; set; }

    public string LocationAddress1 { get; set; }

    public string LocationAddress2 { get; set; }

    public string LocationCity { get; set; }

    public string LocationState { get; set; }

    public string LocationZip { get; set; }

    public string LocationCountry { get; set; }

    public System.DateTime CreateDate { get; set; }

    public bool Active { get; set; }

    public int LocationNumberOfDevice { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CompanyLocation> CompanyLocations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeLocation> EmployeeLocations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeTimeCard> EmployeeTimeCards { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Device> Devices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BookingType> BookingTypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RoomBooking> RoomBookings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Room> Rooms { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TaxInfo> TaxInfoes { get; set; }

}

}
