
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Workbyclocklib.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RoomBookingStatusMaster
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RoomBookingStatusMaster()
    {

        this.RoomBookings = new HashSet<RoomBooking>();

    }


    public int RoomBookingStatusId { get; set; }

    public string RoomBookingStatusName { get; set; }

    public string RoomBookingStatusDesc { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RoomBooking> RoomBookings { get; set; }

}

}
