
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Workbyclocklib.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Room
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Room()
    {

        this.RoomBookings = new HashSet<RoomBooking>();

    }


    public int RoomId { get; set; }

    public string RoomName { get; set; }

    public string RoomDesc { get; set; }

    public int RoomBeds { get; set; }

    public int RoomStatusId { get; set; }

    public int CompanyId { get; set; }

    public int Locationid { get; set; }

    public Nullable<decimal> RoomPrice { get; set; }



    public virtual Company Company { get; set; }

    public virtual Location Location { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RoomBooking> RoomBookings { get; set; }

    public virtual RoomStatusMaster RoomStatusMaster { get; set; }

}

}
