
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Workbyclocklib.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RoomBooking
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RoomBooking()
    {

        this.BookingPayments = new HashSet<BookingPayment>();

    }


    public int RoomBookingId { get; set; }

    public int RoomId { get; set; }

    public int GuestId { get; set; }

    public decimal Price { get; set; }

    public Nullable<System.DateTime> FromDate { get; set; }

    public Nullable<System.DateTime> ToDate { get; set; }

    public int BookingTypeId { get; set; }

    public System.DateTime BookingDate { get; set; }

    public System.DateTime CreateDate { get; set; }

    public int CompanyId { get; set; }

    public int LocationId { get; set; }

    public Nullable<int> RoomBookingStatusId { get; set; }



    public virtual BookingType BookingType { get; set; }

    public virtual Company Company { get; set; }

    public virtual Location Location { get; set; }

    public virtual Room Room { get; set; }

    public virtual Guest Guest { get; set; }

    public virtual RoomBookingStatusMaster RoomBookingStatusMaster { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BookingPayment> BookingPayments { get; set; }

}

}
