
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Workbyclocklib.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TaxInfo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TaxInfo()
    {

        this.BookingTypes = new HashSet<BookingType>();

    }


    public int TaxInfoId { get; set; }

    public string TaxInfoName { get; set; }

    public decimal TaxAmount { get; set; }

    public bool IsPercentage { get; set; }

    public Nullable<int> CompanyId { get; set; }

    public int LocatioId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BookingType> BookingTypes { get; set; }

    public virtual Company Company { get; set; }

    public virtual Location Location { get; set; }

}

}
