
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Workbyclocklib.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int UserId { get; set; }

    public string UserAspNetId { get; set; }

    public string UserFullName { get; set; }

    public string UserPhone { get; set; }

    public string UserAddress1 { get; set; }

    public string UserAddress2 { get; set; }

    public string UserCity { get; set; }

    public string UserState { get; set; }

    public string UserZip { get; set; }

    public string UserCountry { get; set; }

    public System.DateTime CreateDate { get; set; }

    public bool Active { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

}

}
